PREFIX : <http://www.example.org/ns#>

SELECT (COUNT(DISTINCT ?feature) AS ?count)
WHERE {
    ?feature a :FEATURE ;
        :has ?child .
    FILTER (?child NOT IN (:numerical_range, :textual_range))
}
