PREFIX : <http://www.example.org/ns#>

SELECT (AVG(?childCount) AS ?count)
WHERE {
    {
        SELECT ?component (COUNT(?child) AS ?childCount)
        WHERE {
            ?component a :COMPONENT .
            OPTIONAL { ?component :has ?child . }
        }
        GROUP BY ?component
    }
}
