PREFIX : <http://www.example.org/ns#>

SELECT (MIN(?featureCount) AS ?count)
WHERE {
    ?knowledge a :KNOWLEDGE .
    OPTIONAL {
        SELECT ?knowledge
               (COUNT(DISTINCT ?feature) AS ?featureCountRaw)
        WHERE {
            VALUES ?relation {
                :constrains :conditions :consequences }
            ?knowledge ?relation ?feature .
            ?feature a :FEATURE .
        }
        GROUP BY ?knowledge
    }
    BIND(COALESCE(?featureCountRaw, 0) AS ?featureCount)
}
